# Generated by Django 5.2.6 on 2026-09-20 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('total_slots', models.PositiveIntegerField(default=5)),
                ('assigned_slots', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=45)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('current_highest_bid', models.PositiveIntegerField(default=0)),
                ('winning_bid', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='competitions.algorithm')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_label', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('year_of_study', models.CharField(blank=True, max_length=50)),
                ('github_profile', models.CharField(blank=True, max_length=255)),
                ('linkedin_profile', models.CharField(blank=True, max_length=255)),
                ('balance', models.PositiveIntegerField(default=1000)),
                ('coding_started_at', models.DateTimeField(blank=True, null=True)),
                ('coding_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active_participant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_participants', to='competitions.algorithm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('is_winning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='competitions.auction')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='competitions.participant')),
            ],
            options={
                'ordering': ['-amount', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='competitions.participant'),
        ),
        migrations.CreateModel(
            name='ParticipantAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('BID', 'Won via Auction Bid'), ('RANDOM', 'Assigned via Random Allocation')], default='BID', max_length=20)),
                ('winning_bid', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_assignments', to='competitions.algorithm')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_assignment', to='competitions.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=20)),
                ('description', models.TextField(help_text='Detailed problem statement in Markdown')),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('time_limit', models.FloatField(default=2.0, help_text='Time limit in seconds')),
                ('memory_limit', models.PositiveIntegerField(default=256000, help_text='Memory limit in KB')),
                ('sample_test_cases', models.JSONField(blank=True, default=list)),
                ('hidden_test_cases', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='competitions.algorithm')),
            ],
            options={
                'ordering': ['difficulty', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('cpp', 'C++ (GCC)'), ('java', 'Java (OpenJDK)')], default='python', max_length=20)),
                ('source_code', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error (NZEC)'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('SERVER_ERROR', 'Internal Server Error')], db_index=True, default='QUEUED', max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('memory_used', models.PositiveIntegerField(default=0)),
                ('judge0_token', models.CharField(blank=True, max_length=100)),
                ('compile_output', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.participant')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.problem')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_problems', to='competitions.participant')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_assignments', to='competitions.problem')),
            ],
            options={
                'ordering': ['problem__difficulty', 'assigned_at'],
                'unique_together': {('participant', 'problem')},
            },
        ),
    ]
